options:
    area1.region.name: "d1-area1"
    area1.Region: "d1-area1" parsed as region
    prefix: "<< &b&oDungeon&f >> "
    gateBlockType: iron bars
    bossName: "&f&kaaaaaaaa&f"
    gate.block: iron bars
    area1.button.location: getLocation(-86,78,304,world "mvw-test")
    area1.locationA: getLocation(-103,777,243,world "mvw-test")
    area1.locationB: getLocation(-85,88,261,world "mvw-test")
    area1.gate1.locationA: getLocation(-99,81,243, world "mvw-test")
    area1.gate1.locationB: getLocation(-95, 78, 242, world "mvw-test")
    area1.gate2.locationA: getLocation(-89, 81, 261, world "mvw-test")
    area1.gate2.locationB: getLocation(-92, 78, 262, world "mvw-test")
    button.location: getLocation(-94,78,252,world "mvw-test")

on load:
    set {area1.flag.using} to false
    set {area1.flag.usable} to true
    set {area1.wave} to 1
    add "" to {area1.clear.players::*}
    remove "" from {area1.clear.players::*}
    set blocks within {@area1.gate2.locationA} and {@area1.gate2.locationB} to {@gate.block}
    set blocks within {@area1.gate1.locationA} and {@area1.gate1.locationB} to air
    set blocks within {@area1.button.location} and {@area1.button.location} to end portal frame
    set {button.location} to getLocation(-94,78,252,world "mvw-test")
    set blocks within {button.location} and {button.location} to end portal frame
    loop all players:
        if members of {region} contains loop-player:
            execute console command "/rg removemember -w mvw-test d1-area1 %loop-player%"
            remove player from {area1.players::*}
    broadcast type of {region}
    broadcast all living entities where [input is in the region {region}]
    remove all living entities where [input is in the region {region}]
    broadcast "%{@prefix}%&fLoaded &6%script%&7.sk"


command /p-region:
    trigger:
        loop all players:
            send "%region at loop-player% &7%loop-player%"
command /e-region:
    trigger:
        set {_list::*} to getEntitiesFromRegion(region at event-player,event-world)
        loop {_list::*}:
            send "entiy: &f%loop-value%" to event-player

on region enter:
    set {_checkRegion} to checkRegion(region,{@area1.region.name})
    if {_checkRegion} is true:
        execute console command "/rg addmember -w mvw-test d1-area1 %event-player%"
        wait 20 tick
        send "%{@prefix}%&7new Memver &b%event-player% &7(%members of event-region%)" to event-player

on region leave:
    set {_checkRegion} to checkRegion(region,{@area1.region.name})
    if {_checkRegion} is true:
        execute console command "/rg removemember -w mvw-test d1-area1 %event-player%"
        wait 20 tick
        send "%{@prefix}%&7remove Memver &b%event-player% &7(%members of event-region%)" to event-player

        


# 🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶
# 🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶
# 🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶🔶
on right click:
    if clicked block is end portal frame:
        if "%region at player%" contains {@area1.region.name}:
            if {area1.flag.usable} is true:
                delete {region}
                set {_region::*} to region at event-player
                if members of {_region} contains event-player:
                    show spell at the clicked block to event-player
                    set {area1.flag.usable} to false
                    set {area1.flag.using} to true
                    set {area1.players::*} to members of {_region}
                    set {button.location} to location of clicked block
                    set clicked block to air
                    set blocks within {@area1.gate2.locationA} and {@area1.gate2.locationB} to {@gate.block}
                    set blocks within {@area1.gate1.locationA} and {@area1.gate1.locationB} to {@gate.block}
                    loop {area1.players::*}:
                        play explosion at blocks within {@area1.gate1.locationA} and {@area1.gate1.locationB} to loop-value
                        play explosion at blocks within {@area1.gate1.locationA} and {@area1.gate1.locationB} to loop-value
                        play sound "entity.irongolem.hurt" with volume 2 and pitch 0 to loop-value at {@area1.gate1.locationA}
                    wait 40 tick
                    loop {area1.players::*}:
                        play sound "ambient.cave" with volume 1 and pitch 2 to loop-value
                        show mob spawner flames at the clicked block to loop-value
                    wait 40 tick
                    loop {area1.players::*}:
                        play sound "entity.witch.ambient" with volume 1 and pitch 0.2 to loop-value
                        send "%{@bossName}%&6: 我が領土に汚い小ネズミが紛れ込んだか…" to loop-value
                    wait 50 tick
                    loop {area1.players::*}:
                        play sound "entity.witch.ambient" with volume 1 and pitch 0.2 to loop-value
                        send "%{@bossName}%&6: 腹の足しにもならぬようなものに用はない" to loop-value
                    wait 40 tick
                    loop {area1.players::*}:
                        play sound "entity.witch.ambient" with volume 1 and pitch 0 to loop-value
                        send "%{@bossName}%&6: ここで死ぬがよい" to loop-value
                    wait 40 tick
                    loop {area1.players::*}:
                        send "","&6======= &6&lEvent &6=======","&f&7敵&fを全て倒せ！","" to loop-value
                    set {_button.location} to getLocation(-94, 78, 252, world "mvw-test")
                    wait 20 tick
                    loop {area1.players::*}:
                        send subtitle "&6Wave &6&l1" to loop-value for 5 seconds with fadein 0.5 second and fade out 0.5 second
                        play sound "entity.player.swim" with volume 0.5 and pitch 0 to loop-value
                    execute console command "/mm m spawn -s Nuhi:1 1 mvw-test,-98.5,78.5,247.5"
                    execute console command "/mm m spawn -s Nuhi:1 1 mvw-test,-88.5,78.5,257.5"
                    execute console command "/mm m spawn -s Nuhi:1 1 mvw-test,-88.5,78.5,247.5"
                    execute console command "/mm m spawn -s Nuhi:1 1 mvw-test,-98.5,78.5,257.5"

on death of living entity:
    if {region} is set:
        broadcast "area1.region: &7%{region}%"
        broadcast "death entity:  &f%event-entity% &7(not only area1)"
        entity is in the region {region}
        broadcast "death entity:  &f%event-entity% &7(just area1 !!)"
        wait 3 tick
        if {area1.flag.using} is true:
            set {_members::*} to members of region {region}
            set {_entities::*} to all living entities where [input is in the region {region}]
            loop {_members::*}:
                play explosion at location at entity to loop-value
            remove {_members::*} from {_entities::*}
            if number of {_entities::*} <= 0:
                if {area1.wave} is 3:
                    wait 40 tick
                    loop {area1.players::*}:
                        play sound "entity.witch.ambient" with volume 1 and pitch 0.2 to loop-value
                        send "%{@bossName}%&6: やるではないか" to loop-value
                    wait 40 tick
                    loop {area1.players::*}:
                        play sound "entity.witch.ambient" with volume 1 and pitch 0.2 to loop-value
                        send "%{@bossName}%&6: 久々に骨のありそうな人間だ" to loop-value
                    wait 40 tick
                    loop {area1.players::*}:
                        play sound "entity.witch.ambient" with volume 1 and pitch 0.2 to loop-value
                        send "%{@bossName}%&6: 遊んでやろう、次に進むがいい…" to loop-value
                    set {area1.flag.using} to false
                    set {area1.flag.usable} to true
                    set {button.location} to getLocation(-94,78,252,world "mvw-test")
                    set blocks within {@area1.gate2.locationA} and {@area1.gate2.locationB} to air
                    set blocks within {@area1.gate1.locationA} and {@area1.gate1.locationB} to air
                    set {area1.clear.players::*} to {area1.players::*}
                    loop {area1.players::*}:
                        play sound "ambient.cave" with volume 1 and pitch 0 to loop-value
                        play sound "entity.irongolem.hurt" with volume 2 and pitch 0 to loop-value at {@area1.gate2.locationA}
                        play mob spawner flames at blocks within {@area1.gate2.locationA} and {@area1.gate2.locationB} to loop-value
                        stop sound "record.ward" for the loop-value
                    wait 1200 tick
                    set blocks within {button.location} and {button.location} to end portal frame
                    set blocks within {@area1.gate2.locationA} and {@area1.gate2.locationB} to air
                    set blocks within {@area1.gate1.locationA} and {@area1.gate1.locationB} to air
                if {area1.wave} is 2:
                    loop {area1.players::*}:
                        play sound "ambient.cave" with volume 1 and pitch 2 to loop-value
                    wait 40 tick
                    loop {area1.players::*}:
                        play sound "entity.witch.ambient" with volume 1 and pitch 0.2 to loop-value
                        send "%{@bossName}%&6: ほう、やるな" to loop-value
                    wait 40 tick
                    loop {area1.players::*}:
                        play sound "entity.witch.ambient" with volume 1 and pitch 0.2 to loop-value
                        send "%{@bossName}%&6: 少し興味が湧いたぞ" to loop-value
                    wait 40 tick
                    loop {area1.players::*}:
                        play sound "entity.witch.ambient" with volume 1 and pitch 0.2 to loop-value
                        send "%{@bossName}%&6: お前のことを試してやろう" to loop-value
                    set {_button.location} to getLocation(-94, 78, 252, world "mvw-test")
                    wait 20 tick
                    execute console command "/mm m spawn -s NuhiJusou:1 1 mvw-test,-88.5,78.5,247.5"
                    execute console command "/mm m spawn -s NuhiJusou:1 1 mvw-test,-98.5,78.5,257.5"
                    execute console command "/mm m spawn -s NuhiYumi:1 1 mvw-test,-94.5,78.5,252.5"
                    loop {area1.players::*}:
                        send subtitle "&6Wave &6&l3 &7(Final Wave)" to loop-value for 5 seconds with fadein 0.5 second and fade out 0.5 second
                        play sound "entity.player.swim" with volume 0.5 and pitch 0 to loop-value
                    set {area1.wave} to 3
                if {area1.wave} is 1:
                    loop {area1.players::*}:
                        play sound "ambient.cave" with volume 1 and pitch 2 to loop-value
                    wait 40 tick
                    loop {area1.players::*}:
                        play sound "entity.witch.ambient" with volume 1 and pitch 0.2 to loop-value
                        send "%{@bossName}%&6: ふん…少しはできるというわけか" to loop-value
                    wait 40 tick
                    loop {area1.players::*}:
                        play sound "entity.witch.ambient" with volume 1 and pitch 0.2 to loop-value
                        send "%{@bossName}%&6: では、これならどうだ？" to loop-value
                    set {_button.location} to getLocation(-94, 78, 252, world "mvw-test")
                    wait 20 tick
                    execute console command "/mm m spawn -s Nuhi:2 1 mvw-test,-98.5,78.5,247.5"
                    execute console command "/mm m spawn -s Nuhi:2 1 mvw-test,-88.5,78.5,257.5"
                    execute console command "/mm m spawn -s Nuhi:2 1 mvw-test,-88.5,78.5,247.5"
                    execute console command "/mm m spawn -s Nuhi:2 1 mvw-test,-98.5,78.5,257.5"
                    execute console command "/mm m spawn -s NuhiJusou:1 1 mvw-test,-94.5,78.5,252.5"
                    loop {area1.players::*}:
                        send subtitle "&6Wave &6&l2" to loop-value for 5 seconds with fadein 0.5 second and fade out 0.5 second
                        play sound "entity.player.swim" with volume 0.5 and pitch 0 to loop-value
                    set {area1.wave} to 2
        else:
            send "%{@prefix}%area1 isn't using" to attacker
            broadcast "%{@prefix}%area1 isn't using"
    else:
        send "area1.region isn't set" to attacker

on death of player:
    execute console command "/rg removemember -w mvw-test d1-area1 %event-player%"
    wait 20 tick
    send "%{@prefix}%&cYou are dead" to event-player


on death of player:
    {area1.region} is set
    if {area1.flag.using} is true:
        remove player from {area1.players::*}
        broadcast {area1.players::*}
        if number of {area1.players::*} <= 0:
            wait 60 tick
            set {area1.flag.using} to false
            set {area1.flag.usable} to true
            set {area1.wave} to 1
            add "" to {area1.clear.players::*}
            remove "" from {area1.clear.players::*}
            remove all living entities where [input is in the region {area1.region}]
            set blocks within {@area1.gate2.locationA} and {@area1.gate2.locationB} to {@gate.block}
            set blocks within {@area1.gate1.locationA} and {@area1.gate1.locationB} to air
            set blocks within {button.location} and {button.location} to end portal frame
            
on quit:
    {@area1.Region} is set
    if members of {@area1.Region} contains event-player:
        execute console command "/rg removemember -w mvw-test d1-area1 %event-player%"
    if {area1.flag.using} is true:
        remove player from {area1.players::*}
        if number of {area1.players::*} <= 0:
            wait 60 tick
            set {area1.flag.using} to false
            set {area1.flag.usable} to true
            set {area1.wave} to 1
            add "" to {area1.clear.players::*}
            remove "" from {area1.clear.players::*}
            remove all living entities where [input is in the region {region}]
            set blocks within {@area1.gate2.locationA} and {@area1.gate2.locationB} to {@gate.block}
            set blocks within {@area1.gate1.locationA} and {@area1.gate1.locationB} to air
            set blocks within {button.location} and {button.location} to end portal frame
